/* global pywebview */


import './Ticker.sass';
import logo from '../../assets/logo.png';
import { Api, State, useAsyncEffect } from '../../libraries/api';
import { useEffect, useState } from 'react';



export default function Ticker() {
  const [ticker, setTicker] = useState('not called');

  useEffect(() => {
    State.setTicker = setTicker;

  }, []);
  return (
    <div className='ticker-container'>
      <h1>Welcome to pywebview <img className='logo' src={logo} alt='pywebview' /></h1>


      <em>You can freely communicate between Javascript with Python without an HTTP server. This value, for example, is being generated by Python code:</em>
      <strong>{ticker}</strong>
    </div>
  );
}
